Closes #89: Setup Frontend README
UOA-SE701-Group3-2021/3Lancers pull request #100
Opened 2021-03-16 05:33 UTC by AngelaLH

Closes #89 

Frontend README set up containing:
- Prerequisites to install
- Getting started
- Available scripts
- Learn more

2021-03-16 07:38 UTC, RawiriHohepa requested changes
Looks good! Just a small change and a decision for the team to make as a whole over whether to use `npm install` or `npm ci` - happy to approve once those are sorted!

2021-03-16 07:38 UTC, RawiriHohepa commented on telos-frontend/README.md
> +1. Open the command prompt and set the working directory as the `3Lancers` directory of your cloned repository. (`cd 3Lancers`)
can you change the cd command to `cd path/to/3Lancers` just to emphasise that they are navigating to the right folder?

2021-03-16 07:38 UTC, RawiriHohepa commented on telos-frontend/README.md
> +2. Run `npm install` to install all the required dependencies
Are we using `npm install` or `npm ci`? I'm pretty sure either one is fine as long as we keep it consistent among everyone - that may be what was causing the really big package-lock diffs

2021-03-16 08:29 UTC, ambiyu commented on telos-frontend/README.md
> +    - [Lint](https://www.npmjs.com/package/lint)
Should be ESLint

2021-03-17 01:25 UTC, RawiriHohepa commented on telos-frontend/README.md
> +2. Run `npm install` to install all the required dependencies
Based on offline discussion it seems that we'll stick with npm install

2021-03-17 01:26 UTC, RawiriHohepa approved these changes
Looks good now, thanks Angela!

2021-03-17 23:07 UTC, ambiyu approved these changes
LGTM

2021-03-18 00:11 UTC, Milk-Yan approved these changes

2021-03-18 00:16 UTC, merged