Closes #34: Implement API endpoints for TodoList
UOA-SE701-Group3-2021/3Lancers pull request #140
Opened 2021-03-19 22:44 UTC by kyzh0

Closes #34 
Create connection between todo api and db model

2021-03-20 22:58 UTC, flexzy requested changes
The APIs look good! Just need some tests for this endpoint before we can merge this. Have a look at the tests in the integration folder to see how we have started to test the API and database connections.

2021-03-22 03:12 UTC, khal745 approved these changes
LGTM! One spelling error in a comment but not a big deal.

2021-03-22 03:12 UTC, khal745 commented on telos-backend/test/integration/todo_api.test.js
> +  // Check event3 is the same
Nit: Spelling error, should be task3

2021-03-22 04:12 UTC, flexzy approved these changes
LGTM! Ran the tests on my machine and they all passed. Logic looks legit. Nice work!

2021-03-22 05:24 UTC, kyzh0 commented on telos-backend/test/integration/todo_api.test.js
> +  // Check event3 is the same
Fixed, thanks!

2021-03-22 05:24 UTC, merged